export const creatorTypes = {
  GIF_CREATE_REQUEST: 'GIF_CREATE_REQUEST',
  GIF_CREATE_SUCCESS: 'GIF_CREATE_SUCCESS',

  SET_GIF_URL: 'SET_GIF_URL',

  API_ERROR: 'API_ERROR',
  DISMISS_ERROR: 'DISMISS_ERROR',

  START_GIF_CREATION: 'START_GIF_CREATION',
  ABORT_GIF_CREATION: 'ABORT_GIF_CREATION',
  DECREMENT_COUNTDOWN: 'DECREMENT_COUNTDOWN',
  START_GIF_RECORDING: 'START_GIF_RECORDING',
  END_GIF_RECORDING: 'END_GIF_RECORDING',
  ACCEPT_GIF: 'ACCEPT_GIF',
  REJECT_GIF: 'REJECT_GIF',
  RESET_CREATOR: 'RESET_CREATOR',
};

export const settingTypes = {
  SET_VIGNETTE: 'SET_VIGNETTE',
  SET_SPLIT: 'SET_SPLIT',
  SET_CHROMA_COLOR: 'SET_CHROMA_COLOR',
};
