export const discoTypes = {
  GIF_CREATE_REQUEST: 'GIF_CREATE_REQUEST',
  GIF_CREATE_SUCCESS: 'GIF_CREATE_SUCCESS',
  API_ERROR: 'API_ERROR',
  SET_GIF_URL: 'SET_GIF_URL',
};

export const settingTypes = {
  SET_VIGNETTE: 'SET_VIGNETTE',
  SET_SPLIT: 'SET_SPLIT',
  SET_CHROMA_COLOR: 'SET_CHROMA_COLOR',
};
