export const creatorSteps = {
  START: 'START',
  COUNTDOWN: 'COUNTDOWN',
  RECORDING: 'RECORDING',
  ACCEPT_OR_REJECT: 'ACCEPT_OR_REJECT',
  COMPLETE: 'COMPLETE',
};

export const creatorTypes = {
  GIF_CREATE_REQUEST: 'GIF_CREATE_REQUEST',
  GIF_CREATE_SUCCESS: 'GIF_CREATE_SUCCESS',

  SET_GIF_URL: 'SET_GIF_URL',

  API_ERROR: 'API_ERROR',
  DISMISS_ERROR: 'DISMISS_ERROR',

  START_GIF_CREATION: 'START_GIF_CREATION',
  DECREMENT_COUNTDOWN: 'DECREMENT_COUNTDOWN',
  START_GIF_RECORDING: 'START_GIF_RECORDING',
  END_GIF_RECORDING: 'END_GIF_RECORDING',
  RESET_CREATOR: 'RESET_CREATOR',

  INITIALIZE_CREATOR: 'INITIALIZE_CREATOR',
  START_WEBCAM: 'START_WEBCAM',

  ENABLE_PREVIEW: 'ENABLE_PREVIEW',
  DISABLE_PREVIEW: 'DISABLE_PREVIEW',
};
